/**
 * Common constants for all features.
 */
export class CommonConstants {
  /**
   * Spacing between list items.
   */
  static readonly LIST_SPACE: string = '10vp';

  /**
   * A maximum of 4 reviews can be displayed under sm and md device types.
   */
  static readonly LIST_COUNT: number = 4;

  /**
   * Prefix of the reply message.
   */
  static readonly NICKNAME_PREV: string = '@';

  /**
   * Suffix of the reply message.
   */
  static readonly NICKNAME_SUFFIX: string = '：';
}