export class ControlConstants {
  /**
   * Play control value.
   */
  static readonly PLAY: string = 'play';

  /**
   * Pause control value.
   */
  static readonly PAUSE: string = 'pause';

  /**
   * Play next control value.
   */
  static readonly NEXT: string = 'next';

  /**
   * Play previous control value.
   */
  static readonly PREVIOUS: string = 'previous';

  /**
   * review value.
   */
  static readonly REVIEW: string = 'review';

  /**
   * Play mode control value.
   */
  static readonly PLAY_MODE: string = 'playMode';

  /**
   * Play list control value.
   */
  static readonly PLAY_LIST: string = 'playList';
}